#!/usr/bin/env bash
# Copyright (c) 2026 Experiential Labs. All rights reserved.
#
# Idempotent trial-VM boot driver, invoked by the explabs-trial systemd
# oneshot on every boot (cloud-init installs the unit and clones the repo).
#
# Order per boot:
#   1. Mint-once env: Supabase JWT trio persisted at first run, docker/.env
#      written only when missing (the JWT secret is baked into the db volume,
#      so re-minting on a later boot would break every stored credential).
#   2. scripts/integration_stack.sh up: prebuilt mode pulls the published
#      trial-api/trial-web images; build-from-source mode lets the wrapper
#      build the api and web images. NEVER reset: reset destroys the db and
#      storage volumes.
#   3. Wait for api /health, web /api/health, and the gateway worker's
#      /health/ready (the worker needs the seeded catalog's first build, and a
#      cold /v1 call before ready is a COUNTED request, so readiness must
#      precede any smoke).
#   4. One smoke pass, unless a previous boot already completed. The smoke
#      services run with --no-deps, which is why step 3 comes first.
#   5. Start Caddy and apply the public-origin env overrides (merged compose
#      with infra/trial/proxy/compose.proxy.yml), then re-check readiness and
#      HARD-GATE on the public HTTPS endpoint actually answering.
#
# The HTTPS gate is why this script exits nonzero rather than warning: an
# advertised endpoint that never got a certificate is a failed install, not a
# successful one. The systemd unit restarts the driver on failure, so a
# transient Let's Encrypt outage or a slow DNS propagation converges on its
# own; a permanent one leaves the unit `failed` for the operator to find.
# The completion stamp is written LAST, after that gate, so its presence
# always means this instance has served a verified HTTPS endpoint.
#
# Everything is appended to /var/log/explabs-trial-install.log.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
config_dir="/etc/explabs-trial"
trial_env_file="${config_dir}/trial.env"
jwt_env_file="${config_dir}/supabase-jwt.env"
# Written only after the HTTPS gate passes; see the tail of this script.
ready_stamp="${config_dir}/ready"
stack_env_file="${repo_root}/docker/.env"
log_file="/var/log/explabs-trial-install.log"

exec > >(tee -a "${log_file}") 2>&1
echo "[first_boot] starting at $(date -u '+%Y-%m-%dT%H:%M:%SZ') (repo: ${repo_root})" >&2

if [ ! -f "${trial_env_file}" ]; then
  echo "[first_boot] missing ${trial_env_file}; cloud-init must write it before this runs" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "${trial_env_file}"

public_origin="${EXPLABS_TRIAL_PUBLIC_ORIGIN:?trial.env must set EXPLABS_TRIAL_PUBLIC_ORIGIN}"
admin_email="${EXPLABS_TRIAL_ADMIN_EMAIL:?trial.env must set EXPLABS_TRIAL_ADMIN_EMAIL}"
admin_password="${EXPLABS_TRIAL_ADMIN_PASSWORD:?trial.env must set EXPLABS_TRIAL_ADMIN_PASSWORD}"
postgres_password="${EXPLABS_TRIAL_POSTGRES_PASSWORD:?trial.env must set EXPLABS_TRIAL_POSTGRES_PASSWORD}"
api_key="${EXPLABS_TRIAL_API_KEY:?trial.env must set EXPLABS_TRIAL_API_KEY}"
gateway_worker_key="${EXPLABS_TRIAL_GATEWAY_WORKER_KEY:?trial.env must set EXPLABS_TRIAL_GATEWAY_WORKER_KEY}"
project_serving_key="${EXPLABS_TRIAL_PROJECT_SERVING_KEY:?trial.env must set EXPLABS_TRIAL_PROJECT_SERVING_KEY}"
# TLS mode from terraform, the operator's own tls_mode: "trusted" (Let's
# Encrypt) or "self-signed" (Caddy's internal CA). Independent of whether a
# domain is set, which only decides the host the certificate covers.
tls_mode="${EXPLABS_TRIAL_TLS_MODE:?trial.env must set EXPLABS_TRIAL_TLS_MODE}"
api_image="${EXPLABS_TRIAL_API_IMAGE:-}"
web_image="${EXPLABS_TRIAL_WEB_IMAGE:-}"

# Mint the Supabase JWT trio exactly once per instance; the secret signs every
# credential the database stores, so it must be stable across reboots.
if [ ! -f "${jwt_env_file}" ]; then
  echo "[first_boot] minting Supabase JWTs" >&2
  tmp_jwt="$(mktemp)"
  "${repo_root}/infra/trial/scripts/mint_supabase_jwts.sh" > "${tmp_jwt}"
  install -m 0600 "${tmp_jwt}" "${jwt_env_file}"
  rm -f "${tmp_jwt}"
fi
# shellcheck disable=SC1090
source "${jwt_env_file}"

prebuilt="no"
if [ -n "${api_image}" ] && [ -n "${web_image}" ]; then
  prebuilt="yes"
elif [ -n "${api_image}${web_image}" ]; then
  echo "[first_boot] only one of api/web images is set; building BOTH from source instead" >&2
fi

# docker/.env is what scripts/integration_stack.sh sources (set -a) and passes
# to compose as --env-file. Write it once; refresh only when missing.
if [ ! -f "${stack_env_file}" ]; then
  echo "[first_boot] writing ${stack_env_file}" >&2
  umask 177
  cat > "${stack_env_file}" <<EOF
# Generated by infra/trial/scripts/first_boot.sh. Secrets are minted per instance;
# the well-known supabase-demo values from docker/.env.example are never used.
POSTGRES_PASSWORD=${postgres_password}
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

# Host ports stay loopback-relevant only; Caddy on 80/443 is the public entry
# and the cloud firewalls open nothing else.
EXPLABS_WEB_HOST_PORT=3300
EXPLABS_API_HOST_PORT=18080
EXPLABS_SUPABASE_HOST_PORT=55421
EXPLABS_DB_HOST_PORT=55422
EXPLABS_STUDIO_HOST_PORT=55423
EXPLABS_MAILPIT_HOST_PORT=55424
EXPLABS_GATEWAY_WORKER_HOST_PORT=18081

# Pairwise-distinct internal keys (integration_stack.sh enforces this).
EXPLABS_API_KEY=${api_key}
EXPLABS_PROJECT_SERVING_DEPLOYMENT_KEY=${project_serving_key}
EXPLABS_GATEWAY_WORKER_KEY=${gateway_worker_key}
EXPLABS_RELEASE_FAULT_KEY=trial-release-fault-key
EXPLABS_PLATFORM_PROVIDER_REVISION=trial-provider-v1
EXPLABS_PROJECT_SERVING_FIXTURE_MODE=deterministic-v1
EXPLABS_PROJECT_SERVING_FIXTURE_PROJECT_ID=00000000-0000-4000-8000-0000000000a1
EXPLABS_PROJECT_SERVING_FIXTURE_EMBEDDING_DIMENSION=3
EXPLABS_AUTH_ADMIN_EMAIL=${admin_email}
EXPLABS_AUTH_ADMIN_PASSWORD=${admin_password}

# Deterministic project name so the overlay in infra/trial/proxy/compose.proxy.yml
# resolves the same network (\${EXPLABS_STACK_PROJECT_NAME}-network).
EXPLABS_STACK_PROJECT_NAME=explabs-trial
# Consumed by the proxy overlay for EXPLABS_PUBLIC_BACKEND_URL and
# GOTRUE_SITE_URL.
EXPLABS_PUBLIC_ORIGIN=${public_origin}
EOF
  if [ "${prebuilt}" = "yes" ]; then
    cat >> "${stack_env_file}" <<EOF

# Prebuilt public trial images; integration_stack.sh skips its in-compose
# build entirely (GHCR publishes every current application image).
EXPLABS_API_IMAGE=${api_image}
EXPLABS_WEB_IMAGE=${web_image}
EXPLABS_STACK_SKIP_BUILD=1
EOF
  fi
  umask 022
fi

# The compose CLI needs the interpolation env exactly like the wrapper builds
# it: source docker/.env with set -a and pass it as --env-file too.
set -a
# shellcheck disable=SC1090
source "${stack_env_file}"
set +a

compose_merged() {
  docker compose --project-name "${EXPLABS_STACK_PROJECT_NAME}" \
    --env-file "${stack_env_file}" \
    -f "${repo_root}/docker/compose.yml" \
    -f "${repo_root}/infra/trial/proxy/compose.proxy.yml" \
    "$@"
}

echo "[first_boot] starting the stack (integration_stack.sh up; never reset)" >&2
"${repo_root}/scripts/integration_stack.sh" up

# Poll one HTTP endpoint until 2xx or the budget runs out.
wait_for_http() {
  local name="$1" url="$2" budget="$3"
  local deadline
  deadline=$(( $(date +%s) + budget ))
  while true; do
    if curl -fsS --max-time 5 -o /dev/null "${url}"; then
      echo "[first_boot] ${name} is ready (${url})" >&2
      return 0
    fi
    if [ "$(date +%s)" -ge "${deadline}" ]; then
      echo "[first_boot] ${name} still not ready after ${budget}s (${url})" >&2
      return 1
    fi
    echo "[first_boot] waiting for ${name} (${url})" >&2
    sleep 15
  done
}

wait_for_http "api" "http://127.0.0.1:${EXPLABS_API_HOST_PORT}/health" 1200
wait_for_http "web" "http://127.0.0.1:${EXPLABS_WEB_HOST_PORT}/api/health" 1200
# The gateway worker reports ready only after the seeded catalog's first
# build; give it the longest budget.
wait_for_http "gateway-worker" \
  "http://127.0.0.1:${EXPLABS_GATEWAY_WORKER_HOST_PORT}/health/ready" 1800

# One smoke pass per instance. A completed boot (stamp present) skips it, so a
# healthy reboot is fast. Warn-only on failure, deliberately: the dashboard is
# still usable, and the HTTPS gate below is what decides whether this boot
# succeeded. smoke_ok gates the stamp, so a failed smoke is retried on the next
# boot exactly as before.
smoke_ok="no"
if [ -f "${ready_stamp}" ]; then
  echo "[first_boot] last verified boot $(cat "${ready_stamp}"); skipping the smoke" >&2
  smoke_ok="yes"
elif "${repo_root}/scripts/integration_stack.sh" smoke; then
  echo "[first_boot] smoke passed" >&2
  smoke_ok="yes"
else
  echo "[first_boot] WARNING: smoke failed; continuing so the proxy still comes up (details above in ${log_file})" >&2
fi

echo "[first_boot] applying public-origin overrides and starting caddy" >&2
compose_merged up -d --no-build supabase-auth web caddy

# web was just recreated with the public-origin env; confirm it is back, then
# check that Caddy answers on port 80. Self-signed WITHOUT a domain has a
# catch-all :80 block that redirects to HTTPS (308); the three host-scoped
# variants rely on Caddy's own auto-redirect, which does not match a loopback
# probe and answers an empty 200.
wait_for_http "web (post-override)" \
  "http://127.0.0.1:${EXPLABS_WEB_HOST_PORT}/api/health" 600
front_status="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 http://127.0.0.1/health || echo 000)"
case "${front_status}" in
  200 | 301 | 302 | 308)
    echo "[first_boot] caddy front door answered HTTP ${front_status}" >&2
    ;;
  *)
    echo "[first_boot] caddy front door check failed (HTTP ${front_status})" >&2
    exit 1
    ;;
esac

# THE GATE. End-to-end TLS: connect to the loopback but present the public
# host, so Caddy picks the matching certificate and route. public_host is the
# domain when one is set, otherwise the bare IP. -k is keyed off tls_mode
# alone, so it applies to BOTH self-signed cases and neither trusted one; real
# clients trust the internal CA's exported root.crt instead of skipping
# verification. This is a hard gate in all four domain/tls_mode combinations:
# the endpoint terraform advertises must actually answer before the install
# reports success. Budget 15 minutes. A first Let's Encrypt issuance normally
# lands in about a minute, and the rest of the budget absorbs a retried ACME
# order or a DNS record that is still propagating; either self-signed mode
# answers on the first poll, because the internal CA issues locally.
curl_verify=()
if [ "${tls_mode}" = "self-signed" ]; then
  curl_verify=(-k)
fi
public_host="${public_origin#https://}"
tls_budget=900
tls_deadline=$(( $(date +%s) + tls_budget ))
front_tls="failed"
while true; do
  if curl -fsS "${curl_verify[@]}" -o /dev/null --max-time 10 \
    --connect-to "${public_host}:443:127.0.0.1:443" \
    "https://${public_host}/health"; then
    front_tls="ok"
    break
  fi
  if [ "$(date +%s)" -ge "${tls_deadline}" ]; then
    break
  fi
  echo "[first_boot] waiting for HTTPS on ${public_host} (tls_mode=${tls_mode})" >&2
  sleep 10
done
if [ "${front_tls}" != "ok" ]; then
  if [ "${tls_mode}" = "trusted" ]; then
    tls_hint="Let's Encrypt did not issue a certificate: confirm ports 80 and 443 are reachable from the internet, and that any domain you set resolves to this VM."
  else
    tls_hint="Caddy's internal CA did not serve the site: inspect the caddy container's logs."
  fi
  echo "[first_boot] FAILED after ${tls_budget}s: ${public_origin} serves no working HTTPS, so the trial endpoint is unusable. ${tls_hint} Full log: ${log_file}" >&2
  exit 1
fi
echo "[first_boot] caddy front door serves HTTPS for ${public_host}" >&2

# Stamped LAST, and only now: the stamp is the claim that this instance has
# served a verified HTTPS endpoint, and the next boot skips the smoke on it.
# Refreshed every successful boot, so it reads as "last verified".
if [ "${smoke_ok}" = "yes" ]; then
  date -u '+%Y-%m-%dT%H:%M:%SZ' > "${ready_stamp}"
fi

echo "[first_boot] done. Dashboard: ${public_origin} | Admin: ${admin_email}" >&2
