-- Live agent sessions: interactive runs of an agent's champion harness inside
-- a dedicated E2B sandbox, with tools that execute for REAL against the
-- sandbox filesystem (unlike optimization runs, whose tools are answered by
-- the world-model simulation). A `agent_sessions` row is the durable record
-- of one session; `agent_session_events` is its append-only, gapless
-- transcript (the UI's SSE/polling feed reads it); `agent_session_commands`
-- is the user->driver channel (steer/interrupt/end) the driver polls.
--
-- The Modal driver is the single writer of events, fenced by `claim_epoch`:
-- `append_session_event` bumps `last_seq` and inserts atomically only when the
-- caller's epoch matches, so a zombie driver (a duplicate spawn) self-
-- terminates on its next write instead of corrupting the seq sequence.
--
-- Org-scoped, agent-scoped, NO project_id (the project concept is being
-- removed org-wide; sessions are born org-denormalized so nothing here needs
-- to change when that lands). RLS mirrors agents: the service role writes, org
-- members read sessions + events. Spend: a session's priced cost_usd (worker
-- LLM + optionally E2B sandbox seconds) folds into organizations.spend_usd via
-- the same trigger pattern as the other metered tables, and
-- recompute_org_spend is extended to include it.

create type public.agent_session_status as enum (
  'starting',
  'running',
  'ending',
  'ended',
  'failed'
);

create table public.agent_sessions (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents(id) on delete cascade,
  -- Denormalized owning org (filled by a BEFORE INSERT trigger, like
  -- agent_opt_runs); the spend trigger needs it during the agent-delete
  -- cascade when the parent agent row is already gone.
  org_id uuid references public.organizations(id) on delete cascade,
  created_by uuid,
  status public.agent_session_status not null default 'starting',
  -- Human-readable substate while `starting` (creating sandbox / preparing
  -- runtime / starting agent) so the poll renders progress, not a bare spinner.
  starting_detail text,
  -- Short title summarizing the session's opening prompt, generated by a cheap
  -- model when the first user message arrives; null until then (the UI falls
  -- back to the agent model + timestamp).
  title text,
  -- Champion harness version pinned at creation; the session keeps running its
  -- version even as later optimization runs advance the champion.
  harness_version int not null,
  -- Agent-model catalog id snapshot (the pi worker LLM).
  agent_model text not null,
  sandbox_id text,
  -- Dispatch bookkeeping, mirroring agent_opt_runs.
  runtime_backend text,
  runtime_call_id text,
  worker_id text,
  -- Fencing token: claim bumps it; only the current-epoch driver may append.
  claim_epoch int not null default 0,
  -- The single-writer event cursor (gapless per session).
  last_seq bigint not null default 0,
  heartbeat_at timestamptz,
  -- Drives the idle timeout; bumped on genuine activity + viewer attachment.
  last_activity_at timestamptz,
  idle_timeout_s int not null default 600,
  max_duration_s int not null default 7200,
  -- Snapshot of the creator's budget-exemption (platform admin) at creation,
  -- so the per-call budget check has an actor-free answer mid-session.
  budget_exempt boolean not null default false,
  -- Worker-LLM metering, accumulated by the driver.
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  llm_calls int not null default 0,
  sandbox_seconds int,
  -- Priced spend in USD (worker tokens + optionally sandbox seconds); null when
  -- nothing priced yet. Folds into organizations.spend_usd via the trigger.
  cost_usd numeric(12, 6),
  ended_reason text check (
    ended_reason is null
    or ended_reason in (
      'user_ended', 'idle_timeout', 'max_duration', 'budget_exceeded', 'error', 'stalled'
    )
  ),
  error text,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create index agent_sessions_agent_created_idx
  on public.agent_sessions (agent_id, created_at desc);

create index agent_sessions_org_status_idx
  on public.agent_sessions (org_id, status);

-- At most one live session per agent, enforced atomically: two concurrent
-- create requests that both pass the API's read-before-insert guard collide
-- here (the second insert violates this partial unique index) instead of both
-- dispatching a sandbox for the same agent.
create unique index agent_sessions_one_active_per_agent
  on public.agent_sessions (agent_id)
  where status in ('starting', 'running', 'ending');

create table public.agent_session_events (
  session_id uuid not null references public.agent_sessions(id) on delete cascade,
  seq bigint not null,
  ts timestamptz not null default now(),
  -- v1 feed kinds. The web terminal is synthesized client-side from the
  -- tool_call/tool_output/tool_result stream (the agent's bash runs off-PTY),
  -- so there is no raw-PTY 'term' kind; an interactive user shell is a
  -- documented follow-up.
  kind text not null check (
    kind in (
      'user_message', 'assistant_message', 'tool_call', 'tool_output',
      'tool_result', 'submit', 'state', 'status', 'error'
    )
  ),
  payload jsonb not null,
  primary key (session_id, seq)
);

create table public.agent_session_commands (
  id bigint generated always as identity primary key,
  session_id uuid not null references public.agent_sessions(id) on delete cascade,
  actor_id uuid not null,
  kind text not null check (
    kind in ('user_message', 'interrupt', 'end')
  ),
  payload jsonb not null default '{}',
  created_at timestamptz not null default now(),
  consumed_at timestamptz,
  rejected boolean not null default false
);

-- Unconsumed commands only: the driver polls this narrow slice each tick.
create index agent_session_commands_pending_idx
  on public.agent_session_commands (session_id)
  where consumed_at is null;

-- Fill the denormalized org from the agent, so the spend delete-leg works
-- during the agent-delete cascade (fill_opt_run_org precedent).
create function public.fill_session_org()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.org_id is null then
    select agents.org_id into new.org_id
      from public.agents agents
     where agents.id = new.agent_id;
  end if;
  return new;
end;
$$;

create trigger fill_session_org
before insert on public.agent_sessions
for each row execute function public.fill_session_org();

-- Fenced, gapless event append: the single-writer invariant. Bumps last_seq
-- (and term_bytes when the payload carries a byte count) and inserts the event
-- atomically, but only when the caller holds the current claim epoch. A stale
-- epoch (a zombie/duplicate driver) raises instead of writing, so the seq
-- sequence can never fork.
create function public.append_session_event(
  in_session uuid,
  in_epoch int,
  in_kind text,
  in_payload jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_seq bigint;
begin
  -- Also require the session to still be live: if the API reconciled a stale
  -- session as failed (without bumping the epoch), a driver that resumes must
  -- not mutate the transcript or last_seq after the row is already terminal.
  update public.agent_sessions
     set last_seq = last_seq + 1
   where id = in_session
     and claim_epoch = in_epoch
     and status in ('starting', 'running', 'ending')
  returning last_seq into v_seq;
  if v_seq is null then
    raise exception 'stale claim epoch for session %', in_session;
  end if;
  insert into public.agent_session_events (session_id, seq, kind, payload)
    values (in_session, v_seq, in_kind, in_payload);
  return v_seq;
end;
$$;

revoke all on function public.append_session_event(uuid, int, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.append_session_event(uuid, int, text, jsonb) to service_role;

-- Atomic epoch-fenced claim: bump claim_epoch, stamp the worker, and return the
-- new epoch, but only while the session is still `starting`. A re-spawned driver
-- claiming the same row bumps the epoch again, which invalidates the first
-- driver's writes through append_session_event's epoch check. Returns null (no
-- row) when the session is already past `starting`, which the caller treats as
-- "someone else owns this".
create function public.claim_agent_session(in_session uuid, in_worker text)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_epoch int;
begin
  update public.agent_sessions
     set claim_epoch = claim_epoch + 1,
         worker_id = in_worker,
         heartbeat_at = now()
   where id = in_session
     and status = 'starting'
  returning claim_epoch into v_epoch;
  return v_epoch;
end;
$$;

revoke all on function public.claim_agent_session(uuid, text)
  from public, anon, authenticated;
grant execute on function public.claim_agent_session(uuid, text) to service_role;

-- Atomic admission: enforce the concurrency caps and insert the `starting` row
-- in ONE transaction, so two concurrent creates cannot both pass a
-- read-before-insert count check and overshoot the per-org / global cap (the
-- per-agent cap already has the partial unique index as its atomic backstop,
-- but a count cap has no equivalent declarative constraint). A single global
-- advisory lock, released at commit, serializes admission; it is cheap because
-- starting a session is a rare, human-driven action, and taking exactly one
-- lock is deadlock-free. Raises a machine-readable reason
-- (agent_active / org_full / global_full) the API maps to a 409; the API keeps
-- its pre-insert checks as a friendly fast path, with this function the
-- authoritative backstop. Caps are passed in so they stay env-configurable on
-- the API side (a cap <= 0 disables that tier's ceiling).
create function public.admit_agent_session(
  in_agent uuid,
  in_org uuid,
  in_created_by uuid,
  in_harness_version int,
  in_agent_model text,
  in_budget_exempt boolean,
  in_idle_timeout_s int,
  in_max_duration_s int,
  in_org_cap int,
  in_global_cap int
)
returns setof public.agent_sessions
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.agent_sessions;
begin
  perform pg_advisory_xact_lock(hashtext('agent_session_admission'));

  if exists (
    select 1 from public.agent_sessions
     where agent_id = in_agent
       and status in ('starting', 'running', 'ending')
  ) then
    raise exception 'agent_active' using errcode = 'P0001';
  end if;

  if in_org_cap > 0 and (
    select count(*) from public.agent_sessions
     where org_id = in_org
       and status in ('starting', 'running', 'ending')
  ) >= in_org_cap then
    raise exception 'org_full' using errcode = 'P0001';
  end if;

  if in_global_cap > 0 and (
    select count(*) from public.agent_sessions
     where status in ('starting', 'running', 'ending')
  ) >= in_global_cap then
    raise exception 'global_full' using errcode = 'P0001';
  end if;

  insert into public.agent_sessions (
    agent_id, org_id, created_by, harness_version, agent_model,
    budget_exempt, idle_timeout_s, max_duration_s
  ) values (
    in_agent, in_org, in_created_by, in_harness_version, in_agent_model,
    in_budget_exempt, in_idle_timeout_s, in_max_duration_s
  )
  returning * into v_row;
  return next v_row;
end;
$$;

revoke all on function public.admit_agent_session(
  uuid, uuid, uuid, int, text, boolean, int, int, int, int
) from public, anon, authenticated;
grant execute on function public.admit_agent_session(
  uuid, uuid, uuid, int, text, boolean, int, int, int, int
) to service_role;

-- Spend fold: a session's priced cost mirrors the other metered tables.
create function public.track_session_agent_spend()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    perform public.apply_org_spend_delta(old.org_id, -coalesce(old.cost_usd, 0));
  end if;
  if tg_op in ('INSERT', 'UPDATE') then
    perform public.apply_org_spend_delta(new.org_id, coalesce(new.cost_usd, 0));
  end if;
  return null;
end;
$$;

create trigger track_session_agent_spend
after insert or update of org_id, cost_usd or delete on public.agent_sessions
for each row execute function public.track_session_agent_spend();

-- Extend the spend recompute tool to include agent_sessions. Same fold rules
-- as 20260709150000_org_spend_counters.sql, plus the sessions leg.
create or replace function public.recompute_org_spend(target_org uuid)
returns numeric
language plpgsql
security definer
set search_path = ''
as $$
declare
  total numeric;
begin
  select coalesce((
      select sum(coalesce(sessions.cost_usd, 0))
        from public.wm_sessions sessions
       where sessions.org_id = target_org), 0)
       + coalesce((
      select sum(coalesce(rollouts.cost_usd, 0) + coalesce(rollouts.wm_cost_usd, 0))
        from public.wm_rollouts rollouts
       where rollouts.org_id = target_org), 0)
       + coalesce((
      select sum(public.build_usage_spend(jobs.usage))
        from public.build_jobs jobs
       where jobs.org_id = target_org), 0)
       + coalesce((
      select sum(public.opt_run_usage_spend(runs.usage))
        from public.agent_opt_runs runs
       where runs.org_id = target_org), 0)
       + coalesce((
      select sum(coalesce(live.cost_usd, 0))
        from public.agent_sessions live
       where live.org_id = target_org), 0)
    into total;
  update public.organizations set spend_usd = total where id = target_org;
  return total;
end;
$$;

alter table public.agent_sessions enable row level security;
alter table public.agent_session_events enable row level security;
alter table public.agent_session_commands enable row level security;

-- Org members read their sessions; the service role (API + driver) writes.
create policy agent_sessions_select_member
  on public.agent_sessions
  for select
  to authenticated
  using (org_id in (select public.member_org_ids()));

-- Events reach their organization through the session (like agent_opt_runs
-- through agents). Members read; only the service role appends.
create policy agent_session_events_select_member
  on public.agent_session_events
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.agent_sessions sessions
      where sessions.id = agent_session_events.session_id
        and sessions.org_id in (select public.member_org_ids())
    )
  );

-- Commands are written and read exclusively through the service-role API +
-- driver; no direct member access (they carry raw terminal input).
